// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type Request struct {
	Text       string `json:"text"`
	SourceLang string `json:"source_lang"`
	TargetLang string `json:"target_lang"`
}

type Response struct {
	Code       int    `json:"code"`
	Data       string `json:"data"`
	SourceLang string `json:"source_lang"`
	TargetLang string `json:"target_lang"`
}
